export const cards = {
  trenis: {
    name: "Trenis",
    role: "Tank",
    region: "Tsurah",
    img: "/images/trenis.png",
  },
  tsurok: {
    name: "Tsurok",
    role: "Damage",
    region: "Solaris",
    img: "/images/tsurok.png",
  },
  suqah: {
    name: "Suqah",
    role: "Support",
    region: "Tsurah",
    img: "/images/suqah.png",
  },
  reyka: {
    name: "Reyka",
    role: "Damage",
    region: "Tsurah",
    img: "images/reyka.png",
  },
  bornia: {
    name: "Bornia",
    role: "Tank",
    region: "Tsurah",
    img: "/images/bornia.png",
  },
  boneBear: {
    name: "Bone Bear",
    role: "Damage",
    region: "Tsurah",
    img: "/images/bone-bear.png",
  },
  slivus: {
    name: "Slivus",
    role: "Support",
    region: "Solaris",
    img: "/images/slivus.png",
  },
  mythras: {
    name: "Mythras",
    role: "Damage",
    region: "Solaris",
    img: "/images/mythras.png",
  },
  aldor: {
    name: "Aldor",
    role: "Tank",
    region: "Solaris",
    img: "/images/aldor.png",
  },
  sheik: {
    name: "Sheik",
    role: "Support",
    region: "Solaris",
    img: "/images/sheik.png",
  },
  clinka: {
    name: "Clinka",
    role: "Tank",
    region: "Solaris",
    img: "/images/clinka.png",
  },
  wolven: {
    name: "Wolven",
    role: "Damage",
    region: "Solaris",
    img: "/images/wolven.png",
  },
  flimp: {
    name: "Sheik",
    role: "Support",
    region: "Solaris",
    img: "/images/flimp.png",
  },
  bladeGoblin: {
    name: "Blade Goblin",
    role: "Damage",
    region: "Unknown",
    img: "/images/blade-goblin.png",
  },
  gatherGoblin: {
    name: "Gather Goblin",
    role: "Support",
    region: "Unknown",
    img: "/images/gather-goblin.png",
  },
  blockGoblin: {
    name: "Block Goblin",
    role: "Tank",
    region: "Unknown",
    img: "/images/block-goblin.png",
  },
  blistin: {
    name: "Blistin",
    role: "Support",
    region: "Unknown",
    img: "/images/blistin.png",
  },
  balgorf: {
    name: "Balgorf",
    role: "Damage",
    region: "Unknown",
    img: "/images/balgorf.png",
  },
  afghar: {
    name: "afghar",
    role: "Tank",
    region: "Unknown",
    img: "/images/afghar.png",
  },
  sintar: {
    name: "Sintar",
    role: "Damage",
    region: "Unknown",
    img: "/images/sintar.png",
  },
  oldorn: {
    name: "Sheik",
    role: "Tank",
    region: "Unknown",
    img: "/images/oldorn.png",
  },
  lexarm: {
    name: "Lexarm",
    role: "Support",
    region: "Unknown",
    img: "/images/lexarm.png",
  },
};
